// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4555.BoulderGrabber;

import org.usfirst.frc4555.BoulderGrabber.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc4555.BoulderGrabber.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton goGrab;
    public JoystickButton goRelease;
    public JoystickButton goPunch;
    public JoystickButton goReload;
    public JoystickButton goReleasePunch;
    public JoystickButton goReload2;
    public JoystickButton goArmMove;
    public JoystickButton goPickup;
    public JoystickButton goLetDown;
    public Joystick joystick1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        joystick1 = new Joystick(0);
        
        goGrab = new JoystickButton(joystick1, 1);
        goGrab.whileHeld(new Grab());
        goRelease = new JoystickButton(joystick1, 2);
        goRelease.whileHeld(new Release());
        goPunch = new JoystickButton(joystick1, 3);
        goPunch.whenPressed(new Punch());
        goReload = new JoystickButton(joystick1, 3);
        goReload.whenReleased(new Reload());
        goReleasePunch = new JoystickButton(joystick1, 4);
        goReleasePunch.whenPressed(new ReleasePunch());
        goReload2 = new JoystickButton(joystick1, 4);
        goReload2.whenReleased(new Reload2());
        goPickup = new JoystickButton(joystick1, 5);
        goPickup.whenPressed(new Pickup());
        goLetDown = new JoystickButton(joystick1, 6);
        goLetDown.whenPressed(new LetDown());
       
        
        // SmartDashboard Buttons
        SmartDashboard.putData("ReleasePunch", new ReleasePunch());
        SmartDashboard.putData("Grab", new Grab());
        SmartDashboard.putData("Release", new Release());
        SmartDashboard.putData("Punch", new Punch());
        SmartDashboard.putData("Reload", new Reload());
        SmartDashboard.putData("Reload2", new Reload2());
        SmartDashboard.putData("Pickup", new Pickup());
        SmartDashboard.putData("LetDown", new LetDown());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick1() {
        return joystick1;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

